spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
app:
  token:
    secret: fe60f199041040557dc61317117ad37f10d2352cc8f3ccc32abb11056f6a864b
    expirationTime: 200000
    refreshTime: 23123132
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              convert:
                MongoDatabaseFactoryReferenceLoader: TRACE
aws:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  bucket-name: ${BUCKET_NAME}
  url: ${S3_URL}
  region: ${AWS_REGION}
gemini:
  key: ${GEMINI_KEY}
frontend:
  url: ${FRONTEND_URL}
server:
  ssl:
    key-store-type: PKCS12
    key-store: './server-keystore.p12'
    key-store-password: server-password
    key-alias: server-key
    enabled: true