spring:
  data:
    mongodb:
      database: chat
      host: localhost
      port: 27017
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true
app:
  token:
    secret: fe60f199041040557dc61317117ad37f10d2352cc8f3ccc32abb11056f6a864b
    expirationTime: 23123132
    refreshTime: 23123132
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              convert:
                MongoDatabaseFactoryReferenceLoader: TRACE